### ISSUE TITLE
UI improvements in load screen

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#109]
![Image](https://github.com/user-attachments/assets/d7fe572f-8d4e-44ee-93f5-027a1b2fd3b3)

1. help text in BOL Number can be 123456
2. Make help text in the following fields the same font color, font size as help text in status field (light grey)
- Terminal, Supplier, Backup Terminal, Backup Supplier, Assigned Truck, Assigned Trailer, Assigned Driver, Start Date Time and End Date Time

**Comment by Kodecorpui** [comment]
@lsalluri   Issues fixed all the help text changes to semi bold

**Comment by Kumar090680** [comment]
Help text in BOL Number is now displayed as 123456 as expected.

@Kodecorpui : Help Text in Terminal, Backup Terminal, Supplier and Backup Supplier, Assigned Truck, Assigned Trailer and Assigned Driver are still highlighted in black color but, help text in these fields must be in Light Grey as in Status/BOL Number field. Start Date Time and End Date Time can be left AS-IS since, there is no help text for these fields (default sys date will be auto displayed). Please refer below screenshot.


![image](https://github.com/user-attachments/assets/dba8ae2b-b68a-4176-8b34-bca9670520b2)

**Comment by Kodecorpui** [comment]
@lsalluri @Kumar090680   All of the solution's disabled fields are expected to be light gray.

**Comment by Vishnu06051999** [comment]
@Kumar090680 @lsalluri inputText of placeholder is default color

**Comment by Kumar090680** [comment]
@lsalluri  : As per the above comments, closing the issue.
