### ISSUE TITLE
Load editing issues

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#130]
1. I tried editing first row and the compartment is showing blank and not able to select anything
2. When I add all rows, try to edit a row, remove rows and then try to add a product I am getting an error
3. If gross and net is 0 in the truck's compartment, then the category in the requested load should be editable
4. if add all rows for truck or trailer is clicked, we need to default the request loads gross and net to what it is in the compartments capacity. Do not do this logic for add products.

**Comment by Kodecorpui** [comment]
@lsalluri   Issues fixed and Deployed

**Comment by Kumar090680** [comment]
@Kodecorpui : All listed issues are resolved and working as expected. Please check below. Closing this issue.


**Created BOL-20241030-TEST-05 with Diesel as Category, USLD 4 as Product and then Assigned Truck T1986. Since Truck T1986 doesn't have any compartment with Diesel as Category, USLD 4 as Product so, there are no compartments available in the Compartment dropdown list, as expected** 

![image](https://github.com/user-attachments/assets/93cb1bd4-e935-4007-9633-5e9e7bbb09a1)

**5 Compartments in Truck T1986**

![image](https://github.com/user-attachments/assets/c2826d0a-a1d6-4d55-9527-47b0a237c583)

**To view the compartments in the Compartment dropdown, changed the Category and Product as shown below such that compartments are now available in the Compartment dropdown**

![image](https://github.com/user-attachments/assets/7725152a-70f5-4c18-b64e-d4fd4bda69e6)

**Initially when product is added using Add Product, product in the 3rd compartment of Truck T1986 have editable Gross and Net field but, Capacity is not defaulted in these fields as shown below**

![image](https://github.com/user-attachments/assets/a41df25f-4ba7-4bdf-9107-ad070dc51910)

**When Add all Truck Compartments is checked-in, remaining 4 compartments (1,2,4 and 5) were added to the Product Grid as shown below**

![image](https://github.com/user-attachments/assets/ecbdf865-1290-40fe-8b8b-da2e76a3e6c9)

**Trailer TL1981 have 3 compartments with all Gross and Net set to 0 (zero)**

![image](https://github.com/user-attachments/assets/4528822c-14cb-4d2b-af03-7f625f34e23a)

**Truck T1980 have 6 compartments with all Gross and Net set to 0 (zero)**

![image](https://github.com/user-attachments/assets/c3623d9b-398d-487d-9639-1d887ca98c63)

**Created BOL-202410300-TEST-07 with assigned Truck T1980 and Trailer TL1981 which has Category and Product as editable dropdown lists**

![image](https://github.com/user-attachments/assets/e0cf2476-0467-4c05-a5a0-a3692c1f9fc0)

![image](https://github.com/user-attachments/assets/1516207b-5af5-4757-955b-bb8cca66161c)
