### ISSUE TITLE
BOL load preview sliding feature

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#133]

**Comment by SaiAkhil2** [comment]
Adding a Sliding features for BOL Load Showing of  :-   
1.Complete Details of Loads  ,
2.Details of Loaded Products (as like as Product Grid In BOL)
3.Details of Fees 
4.Documents And Instructions too 
Compatable in any screen where BOL Number is displayed by clicking it @lsalluri

**Comment by SaiAkhil2** [comment]
![Image](https://github.com/user-attachments/assets/ab7ff390-91eb-4223-af75-c3121f0f51ad)

**Comment by SaiAkhil2** [comment]
![Image](https://github.com/user-attachments/assets/f8d73273-ed33-41f6-8b68-3255741ccfcb)

**Comment by SaiAkhil2** [comment]
added an Icon beside the items label when user clicks upon it , displays the preview of Current Load Status @lsalluri Can I go with feature by adding icon on it Mam

**Comment by Kumar090680** [comment]
@SaiAkhil2 : BOL Preview is opening in new window upon clicking the icon, as expected. Documents section in BOL preview window is displayed only when loads with complete status are selected, as expected. Please find below observations
@lsalluri  : Please review and share your comments if anything else to be implemented/improved

1. Need to have the collapsible window for BOL/Terminal/Truck Info sections also as shown below
2. To be uniform, all section names to be in upper case
3. **Info** text to be suffixed for Instructions and Documents. Else, retain text info only for BOL since this window is regarding BOL and remove from rest all sections similar to Assigned Truck/Trailer hyperlink in Loads/Orders screen.

**Load in Complete Status with Documents Section**
![image](https://github.com/user-attachments/assets/8d36148b-c6c7-450c-acea-1e4ec0ebb05f)

**New Load without Documents Section**
![image](https://github.com/user-attachments/assets/54e6e38d-02f1-4f71-b249-b888ea551e19)

**Info text missing for Documents and Instructions sections and  BOL Info/Terminal Info/Truck Info are in Lower case**
![image](https://github.com/user-attachments/assets/796e25a9-0557-4732-94f5-53afa7894321)

**Comment by Kumar090680** [comment]
BOL Preview is opening in new window upon clicking the icon, as expected. Documents section in BOL preview window is displayed only when loads with complete status are selected, as expected. Closing this ticket.

• Collapsible window is available for all sections as shown below as expected
• All section names are in upper case  as expected
• Info text is available for BOL/Terminal/Truck sections as expected. 

![image](https://github.com/user-attachments/assets/80c5aafe-1018-44ce-b211-e7d35028418a)
