### ISSUE TITLE
Product Variant - UI

### ISSUE THREAD

**Issue by kpillamyfuelai** [lsalluri/myfuel.ai#31]

**Comment by Kumar090680** [comment]
Product Variants screen is available under Products Sub-Menu in left navigation bar. But, due to lack of privileges, unable to perform any action. Probably this screen must be included in Roles & Permissions screen under Admin role

![image](https://github.com/user-attachments/assets/6dfbbb79-2918-4082-9852-3f7c8d9573b3)
