### ISSUE TITLE
Loading of each screen is taking nearly 5-6 seconds. Performance need to be improved and to be maintained throughout the day

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#56]

**Comment by kv-myfuel** [comment]
@Kumar090680 from api response time I will see and fix it

**Comment by kv-myfuel** [comment]
@Kumar090680 I have fixed it from api response time side further test again and list down api which needs improvement.
there might other reason also which can cause slow loading, UI rendering time and delay due to server region or server down.
expected time must be less then 2 seconds for 25 records in list.

**Comment by Kumar090680** [comment]
@lsalluri : As discussed with Kritesh, screen loading is dependent on 3 factors, API Response Time, UI Load Time and Server Response Time. After API pushes the data to UI, UI will take some time to publish which is known as UI Load Time. All these factors to be considered for screen loading time.


If the above justification is satisfactory, this can be closed
