### ISSUE TITLE
Instructions label change

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#72]
Update instruction labels to:

1. Customer
2. Ship To
3. Driver
4. Order
5. Add new instruction called Accounting

**Comment by kv-myfuel** [comment]
all instruction are now coming in get api of order UI need to be fix to show all

**Comment by kv-myfuel** [comment]
Get api include all type of instructions but UI only shows Customer Instructions please check

**Comment by Kumar090680** [comment]
@kv-myfuel, @Kodecorpui : Instruction Labels in Orders and Loads Screen are as expected. 
In Customers Screen, Customer Label alone is available as expected but, no need to have dropdown list since only 1 label by default Customer must be displayed

**Instruction Labels in Orders Screen:**
![image](https://github.com/user-attachments/assets/278648b1-1c47-4ccb-acd1-ce8223d66b61)

**Instruction Labels in Loads Screen:**
![image](https://github.com/user-attachments/assets/adcce6e5-b5da-48ba-b61d-0c950dfdf90c)

**Customer Label alone is available in Instruction dropdown in Customers Screen (as expected)**
![image](https://github.com/user-attachments/assets/afc6c094-548b-4a98-aae8-2dc1cb7b082e)

**Comment by kc-vamshi** [comment]
1. Displaying all labels in Order
2. Load: Restricted to select only "Load", "Accounting" and "Driver"
3. Customer: fixed loading... issue in customer instruction tab occurred due to change of instruction label.

**Comment by Kumar090680** [comment]
@kc-vamshi : Awaiting build to retest

**Comment by kc-vamshi** [comment]
@Kumar090680 Deployed latest. Please check.

**Comment by Kumar090680** [comment]
Working as expected hence, closing the issue.

**Accounting, Driver and Load instruction types are displayed under Instruction Grid in Loads Screen**

![image](https://github.com/user-attachments/assets/d41df2f2-015e-4c90-bb94-5849cc0c601f)

**Accounting, Customer, Driver, Load, Order and Ship To instruction types are displayed under Instruction Grid in Orders Screen**

![image](https://github.com/user-attachments/assets/c55e5007-7121-40b5-beda-fb33747b1366)

**Customer instruction type alone is displayed under Instruction Grid in Customers Screen**

![image](https://github.com/user-attachments/assets/d5f81303-fb07-425a-b47d-d0347b1606ad)
