### ISSUE TITLE
Scheduler Screen - Add button

### ISSUE THREAD

**Issue by kpillamyfuelai** [lsalluri/myfuel.ai#8]
Add -> Change this to "Add Order" "Add Load" - when Add Order is clicked take user to New Order view, when Add Load is clicked take user to New Load view

**Comment by Kodecorpui** [comment]
Completed deployed @lsalluri garu

**Comment by Kumar090680** [comment]
@lsalluri - **Add Order** and **Add Load** buttons are made available in **Scheduler** screen and when clicked on these buttons, they are re-directed to **Add Order** and **BOL** screens respectively. 

But, can you please clarify if the button to be named as Add BOL or Add Load, since in the above description both these names are used and also please update the description as Scheduler Screen instead of Orders Screen. Attached screenshot for your reference. Issue can be closed.

![Image](https://github.com/user-attachments/assets/2593a327-cefd-4c71-828d-3ad49faff811)
