### ISSUE TITLE
Add instructions section to load similar to order instruction

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#97]
Add an instructions section to the load screen similar to order screen (side by side)
![Image](https://github.com/user-attachments/assets/8243ab5c-8e95-448d-9458-2c0a0402a59e)

![Image](https://github.com/user-attachments/assets/c0eac940-e496-4b52-852c-5e5a5a811dff)

Update driver label to driver note. 

Any notes added to a load or order from the web should show as driver note. If driver note is added at dispatch of load or order, it should appear in the instructions section of the mobile app of the load or order. If a driver adds another note in the app for either load or order, it should create another note (not override the previous one).

**Comment by lsalluri** [comment]
Customer is defaulting for some reason when I try to add instructions. it should remain blank until I choose something.
![Image](https://github.com/user-attachments/assets/ad63b01e-a292-4570-bc5b-76c5a94469c6)

**Comment by kc-vamshi** [comment]
removed default instruction type "customer" in Load.

**Comment by sbatharaju12** [comment]
@backend added instrcution in BOL

**Comment by Vishnu06051999** [comment]
from ul side added the instructions  tab in BOL

**Comment by Kumar090680** [comment]
@lsalluri : Instructions Grid is added adjacent to Documents Grid and below Fee Grid in Load/BOL Creation Screen as expected and no default value is selected. 

Can you please clarify if Driver label to be renamed as Driver Note in the dropdown list (currently Drive label is made available in Orders and Loads Screen) and also is note same as instruction?

**Clarification needed for the below pointer which was mentioned in this ticket**

![image](https://github.com/user-attachments/assets/10f690ae-ad35-436a-aac4-92c2f479631d)


**Instructions Grid is added adjacent to Documents Grid (similar to Orders screen) and there is no default value selected when Instruction is added**

![image](https://github.com/user-attachments/assets/0ac9e728-8e05-4923-a038-fbb2bd2f0cd1)

**Comment by Kumar090680** [comment]
@kc-vamshi, @Vishnu06051999 : Please find below insights from @lsalluri and Karthik Pilla

**25-Oct-2024 :** We want to have instructions and notes separated, but because we don’t have that much time before the go live on Nov 2 we can do that later. For now we can leave it as instructions. I wanted to change it to driver note because we want to capture if driver input something in the app, we want it to reflect in web.

**28-Oct-2024 :** I think we will keep Instructions/Notes in one grid for now. We eventually want to separate this in the future but will wait till after go live. Main reason to change the driver label to driver note is to differentiate that it came from the mobile app (we are calling that section notes in the mobile app and hence calling it driver note).

**29-Oct-2024 :** So, post this change implemented we need to see 2 tabs in Users Create Screen i.e, Instructions and Note to capture respective instructions/notes, details in Note tab while viewing in UI will be readable only and details in Instructions tab while viewing in App will be readable only. Driver can only add/edit Driver Notes from the mobile app

For now, no change is required until 2nd Nov. Please confirm @lsalluri

**Comment by Kumar090680** [comment]
@lsalluri : Please re-open this ticket since, work is pending as per the above comments and also #96 is dependent on this ticket
