### ISSUE TITLE
UI changes in order screen

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#98]
![Image](https://github.com/user-attachments/assets/91b4f52e-018f-4634-bbe5-0799ae06bcf9)
![Image](https://github.com/user-attachments/assets/8662b878-7908-4a6f-bc9e-f274a418fd2c)

Label changes:
Backoffice Order # > Back Office Order #
Create By > Created By
P.O Number > P.O. Number (help text as well)
Purchase order > Purchase Order
Work order > Work Order
Stick readings > Stick Readings
Help text for Address is currently address line 1, city, county, state, zip code, country > Address 1, City, County, State, Zip Code, Country

**Comment by Kumar090680** [comment]
@manju45kk : Please find below issues which still exists,

**Help text in New Address pop-up window is still lower case letters, please update it**
![image](https://github.com/user-attachments/assets/57781e61-6976-4ac7-80fd-7e564d457205)

**Neither unable to cancel nor save New Address pop-up window. Need to refresh the whole page in order to avoid the pop-up**. **Basically, this pop-up window is not necessary at all, since address field is auto populated based on the ShipTo location**
![image](https://github.com/user-attachments/assets/dc001a82-5843-40ca-912c-c73d2c478f93)


**Assets/Fueling Events grid need to be moved right as mentioned by @lsalluri  in the above image**
![image](https://github.com/user-attachments/assets/afc043e3-3b05-474b-830a-9e56506dff3d)

**Header is not found for every product added under Products grid**
![image](https://github.com/user-attachments/assets/e1a4cb22-0412-47c4-9c5e-771ce9ebf945)

**Comment by manju45kk** [comment]
@Kumar090680  - i haave disscussed with @lsalluri  - since these aabove mentioned chnages are not required - u close this ticket
